CREATE TABLE IF NOT EXISTS `#__miniorange_oauth_customer` (
    `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `email` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `admin_phone` VARCHAR(255) NOT NULL,
    `customer_key` VARCHAR(255) NOT NULL,
    `customer_token` VARCHAR(255) NOT NULL,
    `api_key` VARCHAR(255) NOT NULL,
    `login_status` TINYINT(1) DEFAULT 0,
    `status` VARCHAR(255) NOT NULL,
    `oauth_lk` VARCHAR(255) NOT NULL,
    `registration_status` VARCHAR(255) NOT NULL,
    `transaction_id` VARCHAR(255) NOT NULL,
    `licensePlan` VARCHAR(64) NOT NULL,
    `licenseExpiry` TIMESTAMP NULL DEFAULT NULL,
    `supportExpiry` TIMESTAMP NULL DEFAULT NULL,
    `miniorange_fifteen_days_before_lexp` TINYINT(1) DEFAULT 0,
    `miniorange_five_days_before_lexp` TINYINT(1) DEFAULT 0,
    `miniorange_after_lexp` TINYINT(1) DEFAULT 0,
    `miniorange_after_five_days_lexp` TINYINT(1) DEFAULT 0,
    `miniorange_lexp_notification_sent` TINYINT(1) DEFAULT 0,
    `miniorange_oauth_no_notification_sent` TINYINT(1) DEFAULT 0,
    `email_count` INT(11) DEFAULT 0,
    `sms_count` INT(11) DEFAULT 0,
    `noofSP` INT(11) DEFAULT 0,
    `uninstall_feedback` TINYINT(1) DEFAULT 0,
    `cd_plugin` VARCHAR(255) NOT NULL,
    `dno_ssos` INT(11) DEFAULT 0,
    `tno_ssos` INT(11) DEFAULT 0,
    `previous_update` VARCHAR(255) NOT NULL,
    `sso_var` VARCHAR(255) NOT NULL,
    `sso_test` VARCHAR(255) NOT NULL,
    `contact_admin_email` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS `#__miniorange_oauth_config` (
    `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `appname` VARCHAR(124) NOT NULL DEFAULT '',
    `custom_app` VARCHAR(124) NOT NULL DEFAULT '',
    `client_id` VARCHAR(255) NOT NULL DEFAULT '',
    `client_secret` VARCHAR(255) NOT NULL DEFAULT '',
    `app_scope` VARCHAR(255) NOT NULL DEFAULT '',
    `authorize_endpoint` VARCHAR(255) NOT NULL DEFAULT '',
    `access_token_endpoint` VARCHAR(255) NOT NULL DEFAULT '',
    `user_info_endpoint` VARCHAR(255) NOT NULL DEFAULT '',
    `redirecturi` VARCHAR(255) NOT NULL DEFAULT '',
    `email_attr` VARCHAR(64) NOT NULL DEFAULT '',
    `demail_attr` VARCHAR(255) NOT NULL DEFAULT '',
    `display_name_attr` VARCHAR(64) NOT NULL DEFAULT '',
    `username_attr` VARCHAR(64) NOT NULL DEFAULT '',
    `group_name_attr` VARCHAR(64) NOT NULL DEFAULT '',
    `user_contact_attribute` VARCHAR(512) NOT NULL DEFAULT '{"contact":[]}',
    `mapping_value_default` VARCHAR(255) NOT NULL DEFAULT '',
    `role_mapping_key_value` TEXT,
    `enable_role_mapping` TINYINT(1) NOT NULL DEFAULT 0,
    `enable_strict_role_mapping` TINYINT(1) NOT NULL DEFAULT 0,
    `dont_update_role_mapping` TINYINT(1) NOT NULL DEFAULT 0,
    `dont_auto_register` TINYINT(1) NOT NULL DEFAULT 0,
    `enable_restrict_domain` TINYINT(1) NOT NULL DEFAULT 0,
    `restrict_domain_urls` TEXT,
    `login_redirect_url` VARCHAR(255) NOT NULL DEFAULT '',
    `logout_redirect_url` VARCHAR(255) NOT NULL DEFAULT '',
    `enable_custom_admin_login` VARCHAR(32) NOT NULL DEFAULT '',
    `enable_login_link` TINYINT(1) DEFAULT 0,
    `dynamic_link` VARCHAR(124) NOT NULL DEFAULT '',
    `css_sso_link` VARCHAR(255) NOT NULL DEFAULT '',
    `sso_enable` TINYINT(1) NOT NULL DEFAULT 1,
    `sso_button_enable` TINYINT(1) DEFAULT 1,
    `enable_auto_redirect` TINYINT(1) NOT NULL DEFAULT 0,
    `loggers_enable` TINYINT(1) NOT NULL DEFAULT 0,
    `enableGrantType` VARCHAR(126) NOT NULL DEFAULT 'authorization_code',
    `enablePKCE` TINYINT(1) NOT NULL DEFAULT 0,
    `pkce_code_method` VARCHAR(32) NOT NULL DEFAULT 'S256',
    `jwtSignAlgo` VARCHAR(64) NOT NULL DEFAULT 'HSA',
    `jwksUri` VARCHAR(255) NOT NULL DEFAULT '',
    `x509Certificate` TEXT,
    `enableJwtValidation` TINYINT(1) NOT NULL DEFAULT 0,
    `moOauthAttributeMap` VARCHAR(512) NOT NULL DEFAULT '{"profile":[],"field":[]}',
    `access_lgn_urlky` TEXT,
    `after_adm_failure_response` TEXT,
    `custom_failure_destination` TEXT,
    `custom_message_after_fail` TEXT,
    `proxy_server_url` VARCHAR(255) NOT NULL DEFAULT '',
    `proxy_server_port` INT(5) DEFAULT 0,
    `proxy_username` VARCHAR(255) NOT NULL DEFAULT '',
    `proxy_password` VARCHAR(255) NOT NULL DEFAULT '',
    `proxy_set` VARCHAR(20) NOT NULL DEFAULT '',
    `proxy_host_name` VARCHAR(255) NOT NULL DEFAULT '',
    `proxy_port_number` VARCHAR(10) NOT NULL DEFAULT '',
    `port_number` VARCHAR(255) NOT NULL DEFAULT '',
    `username` VARCHAR(255) NOT NULL DEFAULT '',
    `password` VARCHAR(255) NOT NULL DEFAULT '',
    `test_attribute_name` TEXT,
    `in_header_or_body` VARCHAR(64) NOT NULL DEFAULT 'both',
    `httpreferer` VARCHAR(255) NOT NULL DEFAULT '',
    `usrlmt` INT(11) NOT NULL DEFAULT 0,
    `userslim` INT(11) NOT NULL DEFAULT 0,
    `attribute_id` VARCHAR(255) NOT NULL DEFAULT '',
    `attribute_values` VARCHAR(255) NOT NULL DEFAULT '',
    `single_logout_url` VARCHAR(255) NOT NULL DEFAULT '',
    `enable_id_token` TINYINT(1) NOT NULL DEFAULT 0,
    PRIMARY KEY (`id`),
    UNIQUE KEY `unique_custom_app` (`custom_app`)
) DEFAULT COLLATE=utf8_general_ci;


CREATE TABLE IF NOT EXISTS `#__miniorange_oauth_logs`(
    `id` INT AUTO_INCREMENT PRIMARY KEY,
    `timestamp` DATETIME NOT NULL,
    `log_level` VARCHAR(10) NOT NULL,
    `message` TEXT NOT NULL, 
    `file` VARCHAR (255),
    `line_number` INT,
    `function_call`  VARCHAR(255)
) DEFAULT COLLATE=utf8_general_ci;


INSERT IGNORE INTO `#__miniorange_oauth_customer` (`id`, `login_status`, `sso_var`) VALUES (1, FALSE, 'MjU=');
INSERT IGNORE INTO `#__miniorange_oauth_config` (`id`, `usrlmt`) VALUES (1, 10);